name: Build

on: push

env:
  MODULE_PATH: .\src\PesterExtensions
  MODULE_MANIFEST_PATH: .\src\PesterExtensions\PesterExtensions.psd1
  DOTNET_CLI_TELEMETRY_OPTOUT: true 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install PesterExtensions
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module PesterExtensions -RequiredVersion 0.4.0.23
    - name: Generate Module manifest file
      run: .\setup.ps1 -Version 0.1.0
    - name: Run tests
      run: .\tests.ps1 -Version 0.1.0
      
