name: deployment

on:
  workflow_dispatch:

env:
  MODULE_PATH: .\src\PesterExtensions
  DOTNET_CLI_TELEMETRY_OPTOUT: true 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find Tag
        id: latest_tag
        run: .\Get-GitTag.ps1 -OutVariable tag
      - name: Check release is present
        run: gh release view ${{ steps.latest_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Get the previous version of the module
        id: previous_version
        run: .\Get-ExistingPackageVersion.ps1 -OutVariable version
      - name: Clean up version
        id: latest_version
        run: |
          $version = '${{ steps.latest_tag.outputs.tag }}'.Substring(1)
          "::set-output name=version::${Version}"
      - name: Check it's an incremental upgrade
        run: |
          . ".\src\PesterExtensions\Public\Test-SemanticVersionUpdate.ps1"
          Test-SemanticVersionUpdate `
            -Current ${{ steps.previous_version.outputs.version }} `
            -Next ${{ steps.latest_version.outputs.version }} | Should -BeTrue
      - name: Install PesterExtensions
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PesterExtensions -RequiredVersion 0.4.0.23
      - name: Generate Module manifest file
        run: .\setup.ps1 -Version ${{ steps.latest_version.outputs.version }}
      - name: Run tests
        run: .\tests.ps1 -Version ${{ steps.latest_version.outputs.version }}
      - name: Publish to PS Repository
        run: Publish-Module -Path ${{ env.MODULE_PATH }} -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_KEY }}
