name: Publish to Powershell gallery
on: push
env:
  PS_REPOSITORY: github
  DOTNET_CLI_TELEMETRY_OPTOUT: true 
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Module manifest file
      run: .\setup.ps1
    - name: Run tests
      run: Invoke-Pester .\tests\