name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find Tag
        id: tagger
        run: .\Get-GitTag.ps1 -OutVariable tag
      - name: Check release is present
        run: gh release view ${{ steps.tagger.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Get the previous version of the module
        id: version
        run: .\Get-ExistingPackageVersion.ps1 -OutVariable version
      - name: Check it's an incremental upgrade
        run: |
          . .\src\PesterExtensions\Public\Check-SemanticVersion.ps1
          $current = '${{ steps.version.outputs.version }}'
          $next = '${{ steps.tagger.outputs.tag }}'.Substring(1)
          Check-SemanticVersion `
            -Current $current `
            -Next $next | Should -BeTrue
      # - name: Show Tag
      #   run: |
      #     Write-Output "Output from Find Tag: ${{steps.tagger.outputs.tag}}"
