name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find Tag
        id: tagger
        run: |
          foo=$(git fetch --prune && git describe --tags --abbrev=0 --match 'v*' --exclude '*-rc*' 'HEAD~')
          echo "::set-output name=tag::$foo"
      - name: Show Tag
        id: display
        run: |
          echo "Output from Find Tag: ${'${{steps.tagger.outputs.tag}}':1}"
