name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          exclude: 'v.*-rc*'
          commit-ish: 'HEAD~'
      - name: Show Tag
        id: display
        run: |
          echo 'Output from Find Tag: ${{steps.tagger.outputs.tag}}'
